### PR TITLE
Update deploy.yml

### PR DESCRIPTION
**Pull request by Joao-Bittencourt**

### CODE REVIEW

**Comment by Joao-Bittencourt** [comment]
@gooroodev review

**Comment by gooroodev** [comment]
Happy to be tagged, @Joao-Bittencourt!

| 🐞Mistake | 🤪Typo | 🚨Security | 🚀Performance | 💪Best Practices | 📖Readability | ❓Others |
|-----------|--------|------------|---------------|------------------|--------------|----------|
| 1         | 0      | 0          | 0             | 1                | 1            | 0        |

### Summary of Incoming Changes
* ➖ This change removes the `develop` branch from the list of branches that trigger the deployment workflow.

### Identified Issues

| ID  | Type            | Details                                                                 | Severity  | Confidence |
|-----|-----------------|-------------------------------------------------------------------------|-----------|------------|
| 1   | 🐞Mistake       | The `develop` branch trigger has been removed, which may be unintentional. | 🟠Medium  | 🟠Medium   |
| 2   | 💪Best Practices| The `php-version` parameter in `actions/checkout@v3.5.3` is not valid.     | 🟡Low     | 🟠Medium   |
| 3   | 📖Readability   | There is an extra blank line introduced after removing the `develop` branch. | 🟡Low     | 🟢High    |

### Explanation and Fixes

#### Issue 1: Mistake
- **Details**: The `develop` branch trigger has been removed, which might be an oversight and could lead to missing deployments from the `develop` branch.
- **File/Line**: `.github/workflows/deploy.yml` at line 7
- **Fix**:
  ```yaml
  branches:
    - master
    - develop
  ```
- **Explanation**: Re-add the `develop` branch to ensure deployments are triggered on pushes to both `master` and `develop`.

#### Issue 2: Best Practices
- **Details**: The `php-version` parameter in `actions/checkout@v3.5.3` is not valid.
- **File/Line**: `.github/workflows/deploy.yml` at line 16
- **Fix**:
  ```yaml
  - name: Get the latest code
    uses: actions/checkout@v3
  ```
- **Explanation**: The `php-version` parameter should be removed as it is not a valid parameter for `actions/checkout`.

#### Issue 3: Readability
- **Details**: An extra blank line was introduced after removing the `develop` branch.
- **File/Line**: `.github/workflows/deploy.yml` at line 7
- **Fix**:
  ```yaml
  branches:
    - master
  ```
- **Explanation**: Remove the extra blank line to maintain readability and consistency in the YAML file.

### General Review
The code quality is generally good, but there are a few issues:
1. The removal of the `develop` branch trigger appears to be unintentional.
2. The `php-version` parameter in the `actions/checkout` step is invalid.
3. An extra blank line affects readability.

Addressing these issues will ensure the workflow functions correctly and maintains good readability.

--
I **only** arrive when I am mentioned and asked to review the pull request.
Feel free to react or reply to this review!

**Comment by Joao-Bittencourt** [comment]
@gooroodev review

**Comment by gooroodev** [comment]
Here to help, @Joao-Bittencourt! Thanks for the tag!

| 🐞Mistake | 🤪Typo | 🚨Security | 🚀Performance | 💪Best Practices | 📖Readability | ❓Others |
|-----------|--------|------------|---------------|-------------------|--------------|----------|
| 1         | 0      | 0          | 0             | 1                 | 1            | 0        |

### Summary of Incoming Changes
* ➖ Removed deployment trigger for the `develop` branch.
* 💪 Changed the `actions/checkout` version from `v3.5.3` to `v3`.

### Identified Issues
| ID  | Type             | Details                                                                 | Severity  | Confidence |
|-----|------------------|-------------------------------------------------------------------------|-----------|------------|
| 1   | 🐞Mistake        | The `php-version` parameter is used with `actions/checkout`, which is incorrect. | 🟠Medium  | 🔴High     |
| 2   | 💪Best Practices | The `actions/checkout` version should specify the latest minor version. | 🟡Low     | 🟠Medium   |
| 3   | 📖Readability    | Extra trailing space on line `+ master`.                                | 🟡Low     | 🔴High     |

### Explanation of Issues and Fixes

#### 1. 🐞Mistake
**Issue:** The `php-version` parameter is incorrectly used with `actions/checkout`. This parameter is not valid for this action.
**Location:** `.github/workflows/deploy.yml`, line `+7`.
**Fix:** Remove the `php-version` parameter from the `actions/checkout` step.
```yaml
- name: Get the latest code
  uses: actions/checkout@v3
```
**Explanation:** The `actions/checkout` action does not support a `php-version` parameter. This parameter should be removed to avoid configuration errors.

#### 2. 💪Best Practices
**Issue:** The `actions/checkout` version should specify the latest minor version to ensure stability and compatibility.
**Location:** `.github/workflows/deploy.yml`, line `+7`.
**Fix:** Specify the latest minor version explicitly.
```yaml
- name: Get the latest code
  uses: actions/checkout@v3.5.3
```
**Explanation:** Using a specific version tag ensures that the workflow uses a stable and tested version of the action, reducing the risk of unexpected issues.

#### 3. 📖Readability
**Issue:** There is an extra trailing space after the `master` branch name.
**Location:** `.github/workflows/deploy.yml`, line `+4`.
**Fix:** Remove the trailing space.
```yaml
branches:
  - master
```
**Explanation:** Removing unnecessary trailing spaces improves the readability and cleanliness of the code.

### General Review
The code quality is generally good but has a few issues:
1. Incorrect use of parameters with actions.
2. Best practices in versioning should be followed.
3. Minor readability issues like trailing spaces should be avoided.

Addressing these issues will improve the reliability, maintainability, and readability of the workflow configuration.

--
I **only** arrive when I am mentioned and asked to review the pull request.
React or reply to share your thoughts!

**Comment by Joao-Bittencourt** [comment]
@gooroodev review please

**Comment by gooroodev** [comment]
Appreciate being called, @Joao-Bittencourt!

| 🐞Mistake | 🤪Typo | 🚨Security | 🚀Performance | 💪Best Practices | 📖Readability | ❓Others |
|-----------|--------|------------|---------------|------------------|---------------|----------|
| 1         | 0      | 0          | 0             | 1                | 1             | 0        |

### Summary of Changes
* ➖ Removed the `develop` branch from the list of branches that trigger the deployment workflow.
* ❓ Removed the `with` section specifying `php-version: '7.4'` from the `actions/checkout` step.

### Identified Issues

| ID | Type            | Details                                                                 | Severity | Confidence |
|----|-----------------|-------------------------------------------------------------------------|----------|------------|
| 1  | 🐞Mistake       | Removed `with` section for `actions/checkout` step, which is incorrect as `php-version` is not a valid input for this action. | 🟡Low    | 🔴High     |
| 2  | 💪Best Practices| Removed `develop` branch from trigger, potentially missing deployments from this branch. | 🟠Medium | 🟠Medium   |
| 3  | 📖Readability   | Extra trailing whitespace after `master` branch in branches list.        | 🟡Low    | 🟠Medium   |

### Issue Explanations and Fixes

#### Issue 1: Removed `with` section for `actions/checkout` step
* **Explanation**: The `with` section specifying `php-version: '7.4'` was removed, but this input is not valid for `actions/checkout`. It was a mistake to have it in the first place.
* **Fix**: No action needed here as the removal is correct. Ensure no other invalid inputs are added.

#### Issue 2: Removed `develop` branch from trigger
* **Explanation**: By removing the `develop` branch, deployments will not be triggered on pushes to this branch, which may be against the intended workflow.
* **Fix**:
```yaml
on:
  push:
    branches:
      - master
      - develop
```
* **Explanation**: Re-add the `develop` branch to ensure deployments are triggered on pushes to both `master` and `develop`.

#### Issue 3: Extra trailing whitespace after `master` branch
* **Explanation**: The extra trailing whitespace after `master` in the branches list can lead to confusion and is unnecessary.
* **Fix**:
```yaml
on:
  push:
    branches:
      - master
```
* **Explanation**: Remove the trailing whitespace for cleaner and more readable code.

### General Review
The code quality is generally good, but there are a few issues:
1. **Best Practices**: Ensure that all necessary branches are included in the workflow triggers.
2. **Readability**: Avoid unnecessary trailing whitespace to keep the code clean.
3. **Mistake**: Correctly remove invalid inputs for actions to prevent confusion and errors.

Make sure to review and test the workflow thoroughly after making these changes to ensure everything functions as expected.

--
I **only** arrive when I am mentioned and asked to review the pull request.
React or reply to let me know what you think!

**Pull request closed without merging**
